add beans
Slavacheban/springHW pull request #1
Opened 2019-04-28 17:47 UTC by Slavacheban

2019-04-28 18:11 UTC, Anderwerty requested changes

2019-04-28 18:11 UTC, Anderwerty commented on .idea/workspace.xml
>  <project version="4">
This file should not be in the repository.

2019-04-28 18:11 UTC, Anderwerty commented on pom.xml
>  </project>
Please add a blank line at the end of the file.

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/Application.java
> +        System.out.println(shakhtarDonetsk == shakhtarDonetsk2);
Please don't use System.out.println()

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/Application.java
> +        ApplicationContext context = new AnnotationConfigApplicationContext("F:\\Slava\\spring\\src\\main\\java\\beans");
Please use a relative path.

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/DinamoKyev.java
> +    private static Logger LOGGER = Logger.getLogger(ShakhtarDonetsk.class.getName());
You forget the final modifier.

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/ShakhtarDonetsk.java
> +    private static Logger LOGGER = Logger.getLogger(ShakhtarDonetsk.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/DinamoKyev.java
> +public class DinamoKyev implements FootballClub {
Please use DI by using a constructor.
https://www.baeldung.com/spring-injection-lombok

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/ShakhtarDonetsk.java
> +public class ShakhtarDonetsk implements FootballClub {
Please use DI by using a constructor.
https://www.baeldung.com/spring-injection-lombok

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/backs/Isma.java
> +    private static Logger LOGGER = Logger.getLogger(Isma.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/backs/Ramos.java
> +    private static Logger LOGGER = Logger.getLogger(Ramos.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/backs/Srna.java
> +    private static Logger LOGGER = Logger.getLogger(Srna.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/forvards/Adriano.java
> +    private static Logger LOGGER = Logger.getLogger(Adriano.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/forvards/Facundo.java
> +    private static Logger LOGGER = Logger.getLogger(Isma.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/goalkeepers/Boyko.java
> +    private static Logger LOGGER = Logger.getLogger(Boyko.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/goalkeepers/Piat.java
> +    private static Logger LOGGER = Logger.getLogger(Piat.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/halfbacks/Ferna.java
> +    private static Logger LOGGER = Logger.getLogger(Ferna.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/halfbacks/Maycon.java
> +    private static Logger LOGGER = Logger.getLogger(Maycon.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/halfbacks/Silva.java
> +    private static Logger LOGGER = Logger.getLogger(Silva.class.getName());
The same

2019-04-28 18:11 UTC, Anderwerty commented on src/main/java/beans/halfbacks/Taison.java
> +    private static Logger LOGGER = Logger.getLogger(Taison.class.getName());
The same

2019-04-29 08:33 UTC, Slavacheban commented on .idea/workspace.xml
>  <project version="4">
i dont understand what you mean?

2019-04-29 10:33 UTC, Anderwerty commented on .idea/workspace.xml
>  <project version="4">
Please delete this file from repository

2019-04-29 18:07 UTC, Anderwerty requested changes
Why everywhere scope prototype?

2019-04-29 18:07 UTC, Anderwerty commented on pom.xml
>      <artifactId>springHW</artifactId>
Please remove this file from the repository.

2019-04-29 18:07 UTC, Anderwerty commented on springHW.iml
>      </content>
Please remove this file from the repository.

2019-04-29 18:07 UTC, Anderwerty commented on src/main/java/Application.java
> +    public static void main(String[] args) {
Add a blank line between lines 9 and 10.

2019-04-29 18:07 UTC, Anderwerty commented on src/main/java/Application.java
> +
Remove a redundant blank line.

2019-04-29 18:07 UTC, Anderwerty commented on src/main/java/beans/DinamoKyev.java
> +    @Autowired
Add a blank line between lines 30 and 31.

2019-04-29 18:07 UTC, Anderwerty commented on src/main/java/beans/ShakhtarDonetsk.java
> +    @Autowired
Add a blank line between lines 28 and 29.

2019-04-30 07:43 UTC, Anderwerty approved these changes

2019-04-30 07:43 UTC, Anderwerty commented on pom.xml
> +            <version>3.0.5.RELEASE</version>
Why not version 5.1.*?
![image](https://user-images.githubusercontent.com/20267148/56947069-b7584e80-6b34-11e9-8d7f-233d61c9124d.png)

2019-05-30 20:36 UTC, merged